### ISSUE TITLE
crop not happening

### ISSUE THREAD

**Issue by shashankvkt** [vuvko/prepare-oxford-faces#1]
Dear Sir,
I am getting this following error while I run your code
    Olivia_Wilde
    Traceback (most recent call last):
    File "prepare_vggFace.py", line 91, in <module>
    walk_and_crop('/home/soma/Downloads/vgg_face_dataset/files', '/media/soma/Elements    /vgg_faces_cur', '/home/soma/vggFace_cropped/')
     File "prepare_vggFace.py", line 80, in walk_and_crop
      map(lambda f: crop_from_file(os.path.join(instr_dir, f), images_dir, save_dir),         next(os.walk(instr_dir))[2])
      File "prepare_vggFace.py", line 80, in <lambda>
      map(lambda f: crop_from_file(os.path.join(instr_dir, f), images_dir, save_dir),     next(os.walk(instr_dir))[2])
      File "prepare_vggFace.py", line 64, in crop_from_file
        img_map = map_names(next(os.walk(os.path.join(images_dir, person))))
StopIteration

/home/soma/Downloads/vgg_face_dataset/files ---> path contains the text files as in the Vgg face dataset
/media/soma/Elements/vgg_faces_cur --->  path contains the original images (uncropped)

could you kindly advice as how to solve this error...thanks

**Comment by vuvko** [comment]
I have deleted setup for this dataset so it'll take some time for me to try and replicate your issue.

**Comment by shashankvkt** [comment]
Sure thanks. Also i would like to ask you whether you have encountered the below error previously and if yes could you kindly guide me on how to solve it
    ValueError: invalid literal for int() with base 10: 'Olivia_Wilde_00410.jpeg'

This happens in the def map_names function for this line
    idx_map[int(get_clean_name(name))] = name

it is not able to convert dict to int...ive tried many stuffs to solve it but in vain

**Comment by vuvko** [comment]
It's trying to convert string to int and that's odd. IIRC image names were just numbers without person names in it.

**Comment by vuvko** [comment]
Yes, images should be downloaded to <person>/<img_id>.<ext> path, there couldn't be smth like 'Olivia_Wilde_00410.jpeg'.
Are you  sure you downloaded images using prepared links? because I rename them for easier handling later.

**Comment by shashankvkt** [comment]
Thank you very much for your reply...I downloaded the images from the given links itself but renamed them for distinction along with the name. According to your suggestion, I shall try numbering them only and check what happens.
Thaks once again for your feedback!

**Comment by vuvko** [comment]
By the way, there is 2-nd version of this dataset available (without need for downloading via links). [Here](http://www.robots.ox.ac.uk/~vgg/data/vgg_face2/) is the link for more info.

**Comment by shashankvkt** [comment]
It worked!! Thank you very much. Yes, I've had seen the vgg2.
Are you aware of training and testing split for the vgg face dataset?
Thanks once again for the code.

**Comment by vuvko** [comment]
You can split the way you like it. IIRC in paper they use this dataset for training and were validating on LFW and YouTube Faces.
